{
  "hash": "2fec157dc2304a2ad4bbdcba161a9d41",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"HW 01: Bayesian principles\"\nsubtitle: United States Births in 2014\nbibliography: references.bib\n---\n\n\n\n::: callout-important\n## Due date\n\nThis assignment is due on **Thursday, January 30 at 11:45am.** To be considered on time, the following must be done by the due date:\n\n-   Final `.qmd` and `.pdf` files pushed to your GitHub repo\n-   Final `.pdf` file submitted on Gradescope\n:::\n\n# **Getting started**\n\n-   Go to the [biostat725-sp25](https://www.github.com/biostat725-sp25) organization on GitHub. Click on the repo with the prefix **hw-01**. It contains the starter documents you need to complete the homework.\n\n-   Clone the repo and start a new project in RStudio. See the [AE 01 instructions](https://biostat725-sp25.netlify.app/ae/ae-01-mcmc#clone-the-repo-start-new-rstudio-project) for details on cloning a repo and starting a new project in R.\n\n# Packages\n\nThe following packages are used in this assignment:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(openintro)\nlibrary(knitr)\n\n# load other packages as needed\n```\n:::\n\n\n\n# Introduction\n\nEvery year, the United States releases to the public a large dataset containing information on births recorded in the country. This dataset has been of interest to medical researchers who are studying the relation between habits and practices of expectant mothers and the birth of their children. A random sample of 1,000 cases from the dataset released in 2014 can be found in the `births14` data set in the **openintro** R package.\n\nWe will focus on the following variables:\n\n-   `visits`: Number of hospital visits during pregnancy\n\n-   `weight`: Weight of the baby at birth in pounds\n\n-   `habit`: Status of the mother as a `nonsmoker` or a `smoker`\n\nFor this homework, work with the complete case dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbirths14 <- births14[complete.cases(births14), ]\nglimpse(births14)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 794\nColumns: 13\n$ fage           <int> 34, 36, 37, 32, 32, 37, 29, 30, 29, 30, 34, 28, 32, 24,…\n$ mage           <dbl> 34, 31, 36, 31, 26, 36, 24, 32, 26, 34, 27, 22, 25, 20,…\n$ mature         <chr> \"younger mom\", \"younger mom\", \"mature mom\", \"younger mo…\n$ weeks          <dbl> 37, 41, 37, 36, 39, 36, 40, 39, 39, 42, 40, 40, 34, 37,…\n$ premie         <chr> \"full term\", \"full term\", \"full term\", \"premie\", \"full …\n$ visits         <dbl> 14, 12, 10, 12, 14, 10, 13, 15, 11, 14, 16, 20, 20, 10,…\n$ gained         <dbl> 28, 41, 28, 48, 45, 20, 65, 25, 22, 40, 30, 31, 25, 70,…\n$ weight         <dbl> 6.96, 8.86, 7.51, 6.75, 6.69, 6.13, 6.74, 8.94, 9.12, 8…\n$ lowbirthweight <chr> \"not low\", \"not low\", \"not low\", \"not low\", \"not low\", …\n$ sex            <chr> \"male\", \"female\", \"female\", \"female\", \"female\", \"female…\n$ habit          <chr> \"nonsmoker\", \"nonsmoker\", \"nonsmoker\", \"nonsmoker\", \"no…\n$ marital        <chr> \"married\", \"married\", \"married\", \"married\", \"married\", …\n$ whitemom       <chr> \"white\", \"white\", \"not white\", \"white\", \"white\", \"white…\n```\n\n\n:::\n:::\n\n\n\n## Exercises 1-5\n\nDefine a random variable $Y_i$ that represents the number of hospital visits during pregnancy for each woman $i$. Assume that this random variable follows a Poisson distribution with rate $\\lambda$, $Y_i \\stackrel{iid}{\\sim} \\text{Poisson}(\\lambda)$. For a Poisson distribution, the mean and variance of the are equal to $\\lambda$. We are interested in performing statistical inference on $\\lambda$ using a Bayesian approach. A frequently used prior for $\\lambda$ is $\\text{Gamma}(\\text{shape = }a, \\text{rate = }b)$, where $\\mathbb{E}[\\lambda] = a/b$ and $\\mathbb{V}(\\lambda) = a/b^2$.\n\n### Exercise 1\n\nThe researchers have prior knowledge that leads them to believe that $\\lambda$ should have mean 8 and variance 4. What values of $a$ and $b$ should they specify?\n\n::: callout-important\n## Solution\n\nIf $\\mu$ is the mean of $\\lambda$ and $\\sigma^2$ is the variance, it is easy to see that $a = \\mu^2/\\sigma^2$ and $b=\\mu/\\sigma^2$. To obtain a prior distribution with mean 8 (i.e., $\\mu=8$) and variance 4 (i.e., $\\sigma^2=4$), they would need to specify $a=16$ and $b=2$.\n:::\n\n### Exercise 2\n\nUsing the prior specified in **Exercise 1**, what is the a priori probability that $\\lambda$ is greater than 11? This is equivalent to computing $P(\\lambda > 11)$. To find your answer use Monte Carlo sampling. Report your Monte Carlo standard error and make sure it is less than 0.01.\n\n::: callout-important\n## Solution\n\nWe can use Monte Carlo sampling for this. Below I take $S=50,000$ samples from the prior distribution and compute the $P(\\lambda > 11)$.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_samples <- rgamma(50000, shape = 16, rate = 2)\nmean(prior_samples > 11)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.07726\n```\n\n\n:::\n:::\n\n\n\nI also verify that the Monte Carlo standard error is smaller than 0.01.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsqrt(var(prior_samples) / length(prior_samples))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.008933571\n```\n\n\n:::\n:::\n\n\n:::\n\n### Exercise 3\n\nUsing the prior specified in **Exercise 1**, compute the posterior distribution for $\\lambda$, $f(\\lambda | \\mathbf{Y})$, where $\\mathbf{Y}_i = (Y_1,\\ldots,Y_n).$ Recall that the Gamma prior for $\\lambda$ is a conjugate prior, so that the posterior is given by: $f(\\lambda|\\mathbf{Y}) \\sim Gamma(a + \\sum_{i=1}^nY_i,b+n)$. For this analysis, remove missing values of `visits`. Visualize the posterior distribution and report the posterior mean and a 95% credible interval. Provide an interpretation of the posterior distribution within the context of the US births data.\n\n::: callout-important\n## Solution\n\nI will start by obtaining $S=50,000$ samples from the posterior distribution and plotting the samples using a histogram with a density plot (both are not necessary).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvisits <- births14$visits[!is.na(births14$visits)] # remove missing values\nn <- length(visits)\nsum_y <- sum(visits)\nposterior_samples <- rgamma(50000, shape = 16 + sum_y, rate = 2 + n)\ndata.frame(samples = posterior_samples) |> ggplot(aes(x = samples)) + \n  geom_histogram(aes(y = ..density..),\n                 colour = 1, fill = \"white\") +\n  geom_density(lwd = 1.2,\n               linetype = 1,\n               colour = \"black\") + \n  labs(x = expression(lambda),\n       y = \"Density\",\n       title = expression(paste(\"Posterior distribution of \", lambda)),\n       subtitle = \"Rate for number of hospital visits in 2014 for each woman\")\n```\n\n::: {.cell-output-display}\n![](hw-01-creation_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\nThe posterior mean and 95% credible interval can be computed as follows.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummaries <- data.frame(mean = mean(posterior_samples),\n                        lower = quantile(posterior_samples, probs = 0.025),\n                        upper = quantile(posterior_samples, probs = 0.975))\nrownames(summaries) <- \"Posterior Estimates\"\nsummaries |> kable(row.names = TRUE,\n                   col.names = c(\"Mean\", \"2.5%\", \"97.5%\"),\n                   digits = 2,\n                   escape = FALSE)\n```\n\n::: {.cell-output-display}\n\n\n|                    |  Mean|  2.5%| 97.5%|\n|:-------------------|-----:|-----:|-----:|\n|Posterior Estimates | 11.63| 11.39| 11.86|\n\n\n:::\n:::\n\n\n\nThrough this analysis, we estimated the posterior mean number of hospital visits for women during their pregnancies in the United States in 2014 to be 11.63. The 95% credible interval was (11.39, 11.86), indicating that the posterior probability that $\\lambda$ falls between 11.39 and 11.86 is 95%. \n:::\n\n### Exercise 4\n\nWhat is the posterior probability that $\\lambda$ is greater than 11? This is equivalent to computing $P(\\lambda > 11 | \\mathbf{Y})$. Again, use Monte Carlo sampling. Provide an interpretation for this probability in the context of hospital visits.\n\n::: callout-important\n## Solution\n\nThe posterior probability can be computed using the posterior samples computed in **Exercise 3**.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(posterior_samples > 11)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n:::\n\n\n\nThe posterior probability that $\\lambda$ is greater than 11 is equal to 1. This indicates that in 2014, the mean number of hospital visits per pregnancy was almost certainly greater than 11, with a probability of approximately 1.\n:::\n\n### Exercise 5\n\nCreate a figure that includes both the prior and posterior distributions for $\\lambda$. Also, include a figure of the observed data. Use these figures to make a comparison of the prior and posterior probabilities found in **Exercise 2** and **Exercise 4**, respectively. Describe any changes in these two probabilities within the context of the observed data.\n\n::: callout-important\n## Solution\n\nWe can plot the prior and posterior distributions, along with a figure of the observed data.\n\n\n\n::: {.cell layout-ncol=\"2\" layout-align=\"center\"}\n\n```{.r .cell-code}\nn_seq <- 1000\nx <- seq(0, 30, length.out = n_seq)\nprior_dens <- dgamma(x, shape = 16, rate = 2)\nposterior_dens <- dgamma(x, shape = 16 + sum_y, rate = 2 + n)\ndat.fig <- data.frame(x = rep(x, 2), \n                      y = c(prior_dens, posterior_dens),\n                      Type = rep(c(\"Prior\", \"Posterior\"), each = n_seq)\n)\nggplot(dat.fig, aes(x = x, y = y, color = Type)) + \n  geom_line(linewidth = 1.25) + \n  labs(x = expression(pi), \n       y = \"Density\", \n       subtitle = \"Prior and posterior distributions with the following prior: Gamma(a = 16, b = 2)\") + \n  theme(legend.position = \"right\")\n```\n\n::: {.cell-output-display}\n![](hw-01-creation_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=576}\n:::\n\n```{.r .cell-code}\nggplot(births14, aes(x = visits)) + \n  geom_histogram(aes(y = ..density..),\n                 colour = 1, fill = \"white\") +\n  geom_density(lwd = 1.2,\n               linetype = 1,\n               colour = \"black\") + \n  labs(x = \"Number of hospital visits per pregnancy\",\n       y = \"Density\",\n       subtitle = \"Visualization of number of visits per pregnancy in 2014\")\n```\n\n::: {.cell-output-display}\n![](hw-01-creation_files/figure-html/unnamed-chunk-8-2.png){fig-align='center' width=576}\n:::\n:::\n\n\n\nThe prior probability of $\\lambda$ being greater than 11 was equal to 0.08. The posterior probability is 1. The posterior value is nearly 1, as opposed to a prior probability much closer to 0. This makes sense in light of the above figures. In particular, since the observed data has a large sample size (n = 794) the posterior is going to be pulled towards the likelihood. Furthermore, since the mean of the observered data is 11.64, combined with the large sample size, it makes sense that the posterior distribution is pulled above 11.\n:::\n\n## Exercise 6-10\n\nDefine a random variable $Y_i$ that represents the weight of the baby at birth in ounces $i$. Assume that this random variable follows a Poisson distribution with rate $\\lambda$, $Y_i \\stackrel{iid}{\\sim} \\text{Poisson}(\\lambda)$. For a Poisson distribution, the mean and variance of the are equal to $\\lambda$. We are interested in performing statistical inference on $\\lambda$ using a Bayesian approach. A frequently used prior for $\\lambda$ is $\\text{Gamma}(\\text{shape = }a, \\text{rate = }b)$, where $\\mathbb{E}[\\lambda] = a/b$ and $\\mathbb{V}(\\lambda) = a/b^2$.\n\n::: render-commit-push\nYou’re done and ready to submit your work! render, commit, and push all remaining changes. You can use the commit message “Done with Homework 1!”, and make sure you have pushed all the files to GitHub (your Git pane in RStudio should be empty) and that [all]{.underline} documents are updated in your repo on GitHub. The PDF document you submit to Gradescope should be identical to the one in your GitHub repo.\n:::\n\n# Submission\n\nYou will submit the PDF documents for homeworks, and exams in to Gradescope as part of your final submission.\n\n::: callout-warning\nBefore you wrap up the assignment, make sure all documents are updated on your GitHub repo. We will be checking these to make sure you have been practicing how to commit and push changes.\n\nRemember – you must turn in a PDF file to the Gradescope page before the submission deadline for full credit.\n:::\n\nTo submit your assignment:\n\n-   Access Gradescope through the menu on the [BIOSTAT 725 Canvas site.](https://canvas.duke.edu/courses/53305)\n\n-   Click on the assignment, and you’ll be prompted to submit it.\n\n-   Mark the pages associated with each exercise. All of the pages of your lab should be associated with at least one question (i.e., should be “checked”).\n\n-   Select the first page of your .PDF submission to be associated with the *“Workflow & formatting”* section.\n\n# Grading\n\n| Component             | Points |\n|:----------------------|:-------|\n| Ex 1                  | 2      |\n| Ex 2                  | 2      |\n| Ex 3                  | 3      |\n| Ex 4                  | 5      |\n| Ex 5                  | 5      |\n| Ex 6                  | 5      |\n| Ex 7                  | 6      |\n| Ex 8                  | 5      |\n| Ex 9                  | 8      |\n| Ex 10                 | 5      |\n| Workflow & formatting | 4      |\n\nThe \"Workflow & formatting\" grade is to assess the reproducible workflow and document format. This includes having at least 3 informative commit messages, a neatly organized document with readable code and your name and the date updated in the YAML.\n",
    "supporting": [
      "hw-01-creation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}